name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/setup-action@v1
        with:
          jvm: adopt:8
      - uses: coursier/cache-action@v6
      - name: Run tests
        run: sbt -v +test
